apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot-ci-cd-with-github-actions-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-ci-cd-with-github-actions
  template:
    metadata:
      labels:
        app: java-springboot-ci-cd-with-github-actions
    spec:
      containers:
        - name: java-springboot-ci-cd-with-github-actions
          image: java-springboot-ci-cd-with-github-actions:image_tag_to_replace
