name: deploy_pipeline

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name:
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#          VERSION: $(date +'%Y-%m-%d')
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=$DOCKER_PASSWORD

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t martiitram/java-springboot-ci-cd-with-github-actions:$NOW
      - name: list docker images
        run: docker images
      - name: upload image to dockerhub
        run: docker push martiitram/java-springboot-ci-cd-with-github-actions:$NOW


      - name: update_open_shift_image_version
        run: sed -i 's/image_tag_to_replace/$NOW/g' pipelineScripts/deployment.yml

      - name: login to OpenShift
        run: oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
      - name: deploy service to OpenShift
        run: oc apply -f pipelineScripts/service.yml
      - name: deploy deployment to OpenShift
        run: oc apply -f pipelineScripts/deployment.yml
      - name: deploy route to OpenShift
        run: oc apply -f pipelineScripts/route.yml
