name: deploy_pipeline

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name:
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: $(date +'%Y-%m-%d')
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=$DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t martiitram/java-springboot-ci-cd-with-github-actions:$VERSION
      - name: list docker images
        run: docker images
      - name: upload image to dockerhub
        run: docker push martiitram/java-springboot-ci-cd-with-github-actions



      - name: update_open_shift_image_version
        run: sed -i 's/image_tag_to_replace/VERSION/g' pipelineScripts/service_deploy.yml

      - name: login to OpenShift
        run: oc login --token=${{ secrets.OC_TOKEN }} --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      - name: deploy to OpenShift
        run: pipelineScripts/service_deploy.yml
