# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: deploy_pipeline

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name:
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=$DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t java-springboot-ci-cd-with-github-actions
      - name: list docker images
        run: docker images
      - name: upload image to dockerhub
        run: docker push martiitram/java-springboot-ci-cd-with-github-actions
  